name: Code Coverage Runner

on:
  repository_dispatch:
    types: [coverage-command]


jobs:
  codeCoverage:
    runs-on: ubuntu-latest
    steps:

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray

      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          #          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          body: |
            Run coverage!
            [Command run output][1]

            [1]: ${{ steps.vars.outputs.run-url }}

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_PAT }}
          repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Unit Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test -PbuildScan=true -PhideAword=true -PCI=true -PhideSomeBuildVariant=true
        id: gradle
        continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0

      - name: Run Unit Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: jacocoFullTestReport
        continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step

