name: Slash Command Dispatch

on:
  issue_comment:
    # Type "edited" added here for test purposes. Where possible, avoid
    # using to prevent processing unnecessary events.
    types: [created, edited]

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          reaction-type: hooray

      # Basic configuration
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reaction-token: ${{ secrets.GITHUB_TOKEN }}
          commands: coverage
          permission: none


      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

      - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

      - name: Cache Gradle wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle caches
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Unit Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: test -PbuildScan=true -PhideAword=true -PCI=true -PhideSomeBuildVariant=true
        id: gradle

      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          #          issue-number: ${{ github.event.issue.number }}
          comment-id: ${{ github.event.comment.id }}
          body: |
            [Command run output][1]

            [1]: ${{ steps.vars.outputs.run-url }}


      - name: Android Test Report
        uses: asadmansr/android-test-report-action@master
