name: Slash Command Dispatch

on:
  issue_comment:
    # Type "edited" added here for test purposes. Where possible, avoid
    # using to prevent processing unnecessary events.
    types: [created, edited]

jobs:
  slashCommandDispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create URL to the run output
        id: vars
        run: echo ::set-output name=run-url::https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID

      - name: Create comment
          uses: peter-evans/create-or-update-comment@v1
          with:
            #          issue-number: ${{ github.event.issue.number }}
            comment-id: ${{ github.event.comment.id }}
            body: |
              Run coverage!
              [Command run output][1]

              [1]: ${{ steps.vars.outputs.run-url }}

          # Basic configuration
          - name: Slash Command Dispatch
            uses: peter-evans/slash-command-dispatch@v1
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              reaction-token: ${{ secrets.GITHUB_TOKEN }}
              commands: coverage
              permission: none
